- type: entity
  abstract: true
  parent: BaseItem
  id: BasePartInorganic
  name: "body part"
  components:
  - type: Sprite
    sprite: Mobs/Species/Human/parts.rsi
    enableOverrideDir: true
    overrideDir: North
  - type: ThrowingAngle # We add this so that throwing things doesn't make them freak the fuck out by automatically deciding directions.
    angle: 90
  - type: Icon
    sprite: Mobs/Species/Human/parts.rsi
  - type: Damageable
    damageContainer: Inorganic # Shitmed Change
  - type: BodyPart
    partComposition: Inorganic
  - type: SurgeryTool # Shitmed Change
    startSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ1.ogg
    endSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ2.ogg
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
    - Trash


- type: entity
  id: BasePart
  parent: BaseItem
  name: "body part"
  abstract: true
  components:
  - type: Damageable
    damageContainer: Biological # Shitmed Change
  - type: Nerve
  - type: BodyPart
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []
  - type: Appearance
  - type: StaticPrice
    price: 100
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Fat
        Quantity: 3
      - ReagentId: Blood
        Quantity: 10
  - type: Tag
    tags:
      - Trash
      - Meat # Goobstation
  # Shitmed Change Start
  - type: SurgeryTool
    startSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ1.ogg
    endSound:
      path: /Audio/_Shitmed/Medical/Surgery/organ2.ogg
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 110
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 150
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 200
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  # Shitmed Change End

- type: entity
  id: BaseTorso
  name: "torso"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Torso
    # Shitmed Change Start
    toolName: "a torso"
    containerName: "torso_slot"
  - type: ContainerContainer
    containers:
      torso_slot: !type:ContainerSlot {}
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 400
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 400
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
    # Shitmed Change End
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 11
    staminaCost: 12

- type: entity
  abstract: true
  id: BaseChestInorganic
  name: "chest"
  components:
  - type: Sprite
    state: "chest_m"
  - type: Icon
    state: "chest_m"
  - type: BodyPart
    partType: Chest
    # Shitmed Change Start
    toolName: "a chest"
    containerName: "chest_slot"
    children:
      groin:
        id: groin
        type: Groin
      right arm:
        id: right arm
        type: Arm
      left arm:
        id: left arm
        type: Arm
      head:
        id: head
        type: Head
    organs:
      heart:
        id: heart
      lungs:
        id: lungs
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 400
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 400
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  - type: Woundable
    damageContainer: Inorganic
    integrity: 200
    integrityCap: 200
    thresholds:
      Minor: 180
      Moderate: 120
      Severe: 60
      Critical: 30
      Loss: 0
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: Chest
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: Mobs/Effects/bleeding_damage.rsi
  - type: ConsciousnessRequired
    identifier: "chest"
    causesDeath: true
  - type: ContainerContainer
    containers:
      chest_slot: !type:ContainerSlot {}
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 11
    staminaCost: 12

- type: entity
  abstract: true
  id: BaseGroinInorganic
  name: "groin"
  components:
  - type: Sprite
    state: "groin_m"
  - type: Icon
    state: "groin_m"
  - type: BodyPart
    partType: Groin
    # Shitmed Change Start
    toolName: "a groin"
    containerName: "groin_slot"
    children:
      right leg:
        id: right leg
        type: Leg
      left leg:
        id: left leg
        type: Leg
    organs:
      stomach:
        id: stomach
      liver:
        id: liver
      kidneys:
        id: kidneys
  - type: Woundable
    integrity: 100
    integrityCap: 100
    thresholds:
      Minor: 84
      Moderate: 70
      Severe: 55
      Critical: 30
      Loss: 0
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: Groin
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: Mobs/Effects/bleeding_damage.rsi
  - type: ConsciousnessRequired
    identifier: "groin"
    causesDeath: false
  - type: ContainerContainer
    containers:
      groin_slot: !type:ContainerSlot {}
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []

- type: entity
  id: BaseHead
  name: "head"
  parent: BasePart
  abstract: true
  components:
  - type: Damageable
    damageContainer: Biological
  - type: Sprite
    state: "head_m"
  - type: Icon
    state: "head_m"
  - type: BodyPart
    partType: Head
    toolName: "a head" # Shitmed Change
    vital: true
    organs: # Shitmed Change
      brain:
        id: brain
      eyes:
        id: eyes
  - type: Input
    context: "ghost"
  - type: Tag
    tags:
      - Head
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 5
    staminaCost: 5
  - type: Woundable
    boneEntity: BoneNeck
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 50
      Moderate: 35
      Severe: 20
      Critical: 10
      Loss: 0
    damageOnAmputate: # This seemingly arbitrary spread is the result of the default head health (65) subtracted to 200 (death threshold).
      types:
        Bloodloss: 45
        Asphyxiation: 45
        Slash: 45
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: Head
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: Mobs/Effects/bleeding_damage.rsi
  - type: ConsciousnessRequired
    identifier: "head"
    causesDeath: true
  - type: ContainerContainer
    containers:
      mouth_slot: !type:ContainerSlot {}
      Wounds: !type:Container # Shitmed Change
        ents: []
      Bone: !type:Container # Shitmed Change
        ents: []

- type: entity
  id: BaseLeftArm
  name: "left arm"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "l_arm"
  - type: Icon
    state: "l_arm"
  - type: BodyPart
    partType: Arm
    symmetry: Left
    toolName: "a left arm" # Shitmed Change
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 7
    staminaCost: 7
    children: # Shitmed Change
      left hand:
        id: left hand
        type: Hand
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: LArm
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 50
      Moderate: 35
      Severe: 20
      Critical: 10
      Loss: 0

- type: entity
  id: BaseRightArm
  name: "right arm"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "r_arm"
  - type: Icon
    state: "r_arm"
  - type: BodyPart
    partType: Arm
    symmetry: Right
    toolName: "a right arm" # Shitmed Change
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 7
    staminaCost: 7
    children: # Shitmed Change
      right hand:
        id: right hand
        type: Hand
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: RArm
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 50
      Moderate: 35
      Severe: 20
      Critical: 10
      Loss: 0

- type: entity
  id: BaseLeftHand
  name: "left hand"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "l_hand"
  - type: Icon
    state: "l_hand"
  - type: BodyPart
    partType: Hand
    symmetry: Left
    toolName: "a left hand" # Shitmed Change
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 3
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: LHand
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null
  - type: Woundable
    integrity: 50
    integrityCap: 50
    thresholds:
      Minor: 42
      Moderate: 36
      Severe: 26
      Critical: 15
      Loss: 0

- type: entity
  id: BaseRightHand
  name: "right hand"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "r_hand"
  - type: Icon
    state: "r_hand"
  - type: BodyPart
    partType: Hand
    symmetry: Right
    toolName: "a right hand" # Shitmed Change
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 3
  - type: Woundable
    integrity: 50
    integrityCap: 50
    thresholds:
      Minor: 42
      Moderate: 36
      Severe: 26
      Critical: 15
      Loss: 0
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: RHand
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null

- type: entity
  id: BaseLeftLeg
  name: "left leg"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "l_leg"
  - type: Icon
    state: "l_leg"
  - type: BodyPart
    partType: Leg
    symmetry: Left
    toolName: "a left leg" # Shitmed Change
  - type: MovementBodyPart
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 8
    staminaCost: 9
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: LLeg
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 50
      Moderate: 35
      Severe: 20
      Critical: 10
      Loss: 0

- type: entity
  id: BaseRightLeg
  name: "right leg"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "r_leg"
  - type: Icon
    state: "r_leg"
  - type: BodyPart
    partType: Leg
    symmetry: Right
    toolName: "a right leg" # Shitmed Change
  - type: MovementBodyPart
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 8
    staminaCost: 9
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: RLeg
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: Mobs/Effects/bleeding_damage.rsi
  - type: Woundable
    integrity: 65
    integrityCap: 65
    thresholds:
      Minor: 50
      Moderate: 35
      Severe: 20
      Critical: 10
      Loss: 0

- type: entity
  id: BaseLeftFoot
  name: "left foot"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "l_foot"
  - type: Icon
    state: "l_foot"
  - type: BodyPart
    partType: Foot
    symmetry: Left
    toolName: "a left foot" # Shitmed Change
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 4
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: LFoot
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null
  - type: Woundable
    integrity: 50
    integrityCap: 50
    thresholds:
      Minor: 42
      Moderate: 36
      Severe: 26
      Critical: 15
      Loss: 0

- type: entity
  id: BaseRightFoot
  name: "right foot"
  parent: BasePart
  abstract: true
  components:
  - type: Sprite
    state: "r_foot"
  - type: Icon
    state: "r_foot"
  - type: BodyPart
    partType: Foot
    symmetry: Right
    toolName: "a right foot" # Shitmed Change
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 4
  - type: WoundableVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    occupiedLayer: RFoot
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
    bleedingOverlay: null
  - type: Woundable
    integrity: 50
    integrityCap: 50
    thresholds:
      Minor: 42
      Moderate: 36
      Severe: 26
      Critical: 15
      Loss: 0
